import os

PYTHONPATH = os.environ['PYTHONPATH']
TRAIN_SCRIPT_PATH = f"{PYTHONPATH}{os.environ['TRAIN_SCRIPT_PATH']}"
PREDICT_SCRIPT_PATH = f"{PYTHONPATH}{os.environ['PREDICT_SCRIPT_PATH']}"
MODEL_PATH = f"{PYTHONPATH}{os.environ['MODEL_PATH']}"
TRAIN_DATA_PATH = f"{PYTHONPATH}{os.environ['TRAIN_DATA']}"
PREDICT_DATA_PATH = f"{PYTHONPATH}{os.environ['PREDICT_DATA']}"
